server:
  port: ${PORT:8082}

info:
  app:
    name: pricing-service

spring:
  application:
    name: pricing-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:pricedata

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
    service-url:
      default-zone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
  instance:
    preferIpAddress: true

# Custom logging settings
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org:
      springframework: ${LOG_LEVEL:INFO}
